export const FORMAL_BUSINESS_EVENT_TYPES = [
  "mail.reply_verified",
  "mail.commitment_verified",
  "deadline.quote",
  "deadline.contract",
  "deadline.sample",
  "deadline.content",
  "risk.detected",
  "approval_or_material.missing",
  "lead.created",
  "lead.converted",
  "lead.reply_received",
  "lead.followup_due",
  "lead.sample_requested",
  "lead.intent_confirmed",
  "lead.high_potential_detected",
  "coop.created",
  "coop.contract_requested",
  "kol.sample_shipment_requested",
  "kol.sample_reship_requested",
  "kol.script_submitted",
  "kol.script_revision_requested",
  "kol.schedule_change_requested",
  "kol.production_deadline_near",
  "kol.production_delayed",
  "kol.deliverable_submitted",
  "kol.publish_scheduled",
  "kol.publish_verified",
  "kol.settlement_due",
  "kol.invoice_received",
  "kol.sentiment_negative",
  "kol.violation_detected",
  "kol.dispute_raised",
  "kol.settlement_completed",
] as const;

export type FormalBusinessEventType = typeof FORMAL_BUSINESS_EVENT_TYPES[number];

export const FORMAL_BUSINESS_EVENT_TYPE_SET = new Set<string>(FORMAL_BUSINESS_EVENT_TYPES);

export const FORMAL_BUSINESS_EVENT_LABELS: Record<FormalBusinessEventType, string> = {
  "mail.reply_verified": "已验证邮件回复",
  "mail.commitment_verified": "已验证邮件承诺",
  "deadline.quote": "报价期限",
  "deadline.contract": "合同期限",
  "deadline.sample": "样品期限",
  "deadline.content": "内容期限",
  "risk.detected": "风险事件",
  "approval_or_material.missing": "审批或资料缺失",
  "lead.created": "线索建档",
  "lead.converted": "线索转化",
  "lead.reply_received": "达人回复",
  "lead.followup_due": "跟进到期",
  "lead.sample_requested": "索要样品",
  "lead.intent_confirmed": "意向确认",
  "lead.high_potential_detected": "高潜线索",
  "coop.created": "合作项目创建",
  "coop.contract_requested": "请求合同",
  "kol.sample_shipment_requested": "申请寄样",
  "kol.sample_reship_requested": "申请补寄",
  "kol.script_submitted": "脚本已提交",
  "kol.script_revision_requested": "要求改稿",
  "kol.schedule_change_requested": "排期变更申请",
  "kol.production_deadline_near": "临近交付期",
  "kol.production_delayed": "拍摄延期",
  "kol.deliverable_submitted": "交付物已提交",
  "kol.publish_scheduled": "已排期发布",
  "kol.publish_verified": "发布已核验",
  "kol.settlement_due": "结算到期",
  "kol.invoice_received": "收到发票",
  "kol.sentiment_negative": "负面舆情",
  "kol.violation_detected": "违规检测",
  "kol.dispute_raised": "纠纷发起",
  "kol.settlement_completed": "结算完成",
};
