[Service]
WorkingDirectory=/home/ecs-user/kol-releases/task-operations-EXRuCX5v
Environment=LINGONG_DATA=/home/ecs-user/kol/data
ExecStart=
ExecStart=/home/ecs-user/kol-releases/task-operations-EXRuCX5v/scripts/start.sh
