import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { Client } from "pg";

const require = createRequire(import.meta.url);

type SqliteStatement = { all: (...args: unknown[]) => Array<Record<string, unknown>> };
type SqliteDatabase = { prepare: (sql: string) => SqliteStatement; close: () => void };
type Column = { cid: number; name: string; type: string; notnull: number; dflt_value: string | null; pk: number };
type Index = { seq: number; name: string; unique: number; origin: string; partial: number };
type ForeignKey = { id: number; seq: number; table: string; from: string; to: string; on_update: string; on_delete: string };
export type MigrationFingerprintColumn = Pick<Column, "name" | "type">;

export type MigrationTableReport = { table: string; rows: number; fingerprint: string };
export type SqlitePostgresMigrationReport = {
  source: string;
  target: string;
  tables: MigrationTableReport[];
  total_rows: number;
  verified: boolean;
};

function quote(identifier: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(identifier)) throw new Error(`Unsafe SQL identifier: ${identifier}`);
  return `"${identifier}"`;
}

function openSqliteReadOnly(file: string): SqliteDatabase {
  const Database = require("better-sqlite3") as new (path: string, options?: { readonly?: boolean; fileMustExist?: boolean }) => SqliteDatabase;
  return new Database(file, { readonly: true, fileMustExist: true });
}

function sqliteTables(db: SqliteDatabase): string[] {
  return db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    .all()
    .map((row) => String(row.name));
}

function columns(db: SqliteDatabase, table: string): Column[] {
  return db.prepare(`PRAGMA table_info(${quote(table)})`).all() as Column[];
}

function mapType(sqliteType: string): string {
  const type = String(sqliteType || "TEXT").toUpperCase();
  if (type.includes("INT")) return "BIGINT";
  if (type.includes("REAL") || type.includes("FLOA") || type.includes("DOUB")) return "DOUBLE PRECISION";
  if (type.includes("BLOB")) return "BYTEA";
  if (type.includes("NUM") || type.includes("DEC")) return "NUMERIC";
  if (type.includes("DATE") || type.includes("TIME")) return "TEXT";
  return "TEXT";
}

function defaultValue(value: string | null): string {
  if (value == null) return "";
  const source = String(value).trim();
  if (!source || /^NULL$/i.test(source)) return " DEFAULT NULL";
  if (/^\(?strftime\(/i.test(source) || /^\(?datetime\(/i.test(source)) return " DEFAULT CURRENT_TIMESTAMP";
  return ` DEFAULT ${source.replace(/\bIFNULL\s*\(/gi, "COALESCE(")}`;
}

function createTableSql(table: string, tableColumns: Column[]): string {
  const primary = tableColumns.filter((column) => Number(column.pk) > 0).sort((a, b) => a.pk - b.pk);
  const singleIntegerPrimary = primary.length === 1 && /INT/i.test(primary[0].type || "");
  const definitions = tableColumns.map((column) => {
    const identity = singleIntegerPrimary && column.name === primary[0]?.name
      ? "BIGINT GENERATED BY DEFAULT AS IDENTITY"
      : mapType(column.type);
    const notNull = Number(column.notnull) || Number(column.pk) ? " NOT NULL" : "";
    return `${quote(column.name)} ${identity}${notNull}${defaultValue(column.dflt_value)}`;
  });
  if (primary.length) definitions.push(`PRIMARY KEY (${primary.map((column) => quote(column.name)).join(", ")})`);
  return `CREATE TABLE ${quote(table)} (${definitions.join(", ")})`;
}

function rewriteIndexSql(sql: string): string {
  return sql
    .replace(/\bIFNULL\s*\(/gi, "COALESCE(")
    .replace(/\bAUTOINCREMENT\b/gi, "")
    .replace(/\bCREATE\s+(UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z_][\w]*)\s+ON\s+([A-Za-z_][\w]*)/i,
      (_all, unique, name, table) => `CREATE ${unique || ""}INDEX IF NOT EXISTS ${quote(name)} ON ${quote(table)}`);
}

function indexSql(db: SqliteDatabase, table: string, tableColumns: Column[]): string[] {
  const result: string[] = [];
  const names = new Set<string>();
  for (const index of db.prepare(`PRAGMA index_list(${quote(table)})`).all() as Index[]) {
    if (index.origin === "pk") continue;
    const info = db.prepare(`PRAGMA index_info(${quote(index.name)})`).all() as Array<{ seqno: number; cid: number; name: string | null }>;
    const sourceSql = db.prepare("SELECT sql FROM sqlite_master WHERE type='index' AND name=?").all(index.name)[0]?.sql;
    if (sourceSql) {
      result.push(rewriteIndexSql(String(sourceSql)));
      names.add(index.name);
      continue;
    }
    const usable = info.map((entry) => entry.name).filter((entry): entry is string => Boolean(entry));
    if (!usable.length) continue;
    const base = index.name.startsWith("sqlite_autoindex_")
      ? `${index.unique ? "ux" : "ix"}_${table}_${usable.join("_")}`
      : index.name;
    const indexName = names.has(base) ? `${base}_${names.size}` : base;
    names.add(indexName);
    const allColumns = new Set(tableColumns.map((column) => column.name));
    if (usable.some((column) => !allColumns.has(column))) continue;
    result.push(`CREATE ${index.unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS ${quote(indexName)} ON ${quote(table)} (${usable.map(quote).join(", ")})`);
  }
  return result;
}

function foreignKeys(db: SqliteDatabase, table: string): ForeignKey[][] {
  const grouped = new Map<number, ForeignKey[]>();
  for (const key of db.prepare(`PRAGMA foreign_key_list(${quote(table)})`).all() as ForeignKey[]) {
    const group = grouped.get(key.id) || [];
    group.push(key);
    grouped.set(key.id, group);
  }
  return [...grouped.values()].map((group) => group.sort((a, b) => a.seq - b.seq));
}

function foreignKeySql(table: string, key: ForeignKey[], ordinal: number): string {
  const first = key[0];
  const source = key.map((part) => quote(part.from)).join(", ");
  const target = key.map((part) => quote(part.to)).join(", ");
  const update = first.on_update && first.on_update.toUpperCase() !== "NO ACTION" ? ` ON UPDATE ${first.on_update}` : "";
  const del = first.on_delete && first.on_delete.toUpperCase() !== "NO ACTION" ? ` ON DELETE ${first.on_delete}` : "";
  return `ALTER TABLE ${quote(table)} ADD CONSTRAINT ${quote(`fk_${table}_${ordinal}`)} FOREIGN KEY (${source}) REFERENCES ${quote(first.table)} (${target})${update}${del}`;
}

function canonical(value: unknown, type: string): string {
  if (value === null || value === undefined) return "null";
  if (Buffer.isBuffer(value)) return `buffer:${value.toString("base64")}`;
  const normalizedType = String(type || "TEXT").toUpperCase();
  // `pg` returns BIGINT/NUMERIC as strings while better-sqlite3 returns the
  // same values as JS numbers. Compare the declared SQLite representation,
  // rather than the respective driver representation, so a lossless copy is
  // not rejected merely because its reader has a different scalar policy.
  if (normalizedType.includes("INT")) {
    try { return `integer:${BigInt(String(value).trim()).toString()}`; } catch { return `integer:${String(value).trim()}`; }
  }
  if (normalizedType.includes("REAL") || normalizedType.includes("FLOA") || normalizedType.includes("DOUB")) {
    const number = Number(value);
    if (Number.isNaN(number)) return "float:NaN";
    if (number === Infinity) return "float:Infinity";
    if (number === -Infinity) return "float:-Infinity";
    return `float:${number.toString()}`;
  }
  if (normalizedType.includes("NUM") || normalizedType.includes("DEC")) {
    const number = Number(value);
    return Number.isFinite(number) ? `numeric:${number.toString()}` : `numeric:${String(value).trim()}`;
  }
  if (typeof value === "number" || typeof value === "bigint") return String(value);
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

/** Deterministic data fingerprint after SQLite's declared scalar semantics. */
export function migrationFingerprint(rows: Array<Record<string, unknown>>, orderedColumns: MigrationFingerprintColumn[]): string {
  const hash = createHash("sha256");
  // SQLite's BINARY collation and a PostgreSQL database's locale collation may
  // order identical text primary keys differently (notably for CJK creator
  // data). Hash a sorted canonical row multiset instead of trusting either
  // database's ORDER BY semantics; duplicates remain present in the multiset.
  const records = rows
    .map((row) => orderedColumns.map((column) => canonical(row[column.name], column.type)).join("\u001f"))
    .sort();
  for (const record of records) hash.update(`${record}\n`);
  return hash.digest("hex");
}

function mismatchedFingerprintColumns(
  sourceRows: Array<Record<string, unknown>>,
  targetRows: Array<Record<string, unknown>>,
  tableColumns: MigrationFingerprintColumn[],
): string[] {
  return tableColumns
    .filter((column) => migrationFingerprint(sourceRows, [column]) !== migrationFingerprint(targetRows, [column]))
    .map((column) => column.name);
}

function orderedRowsSql(table: string, tableColumns: Column[]): string {
  const primary = tableColumns.filter((column) => column.pk > 0).sort((a, b) => a.pk - b.pk);
  const order = (primary.length ? primary : tableColumns).map((column) => quote(column.name)).join(", ");
  return `SELECT * FROM ${quote(table)} ORDER BY ${order}`;
}

async function copyRows(client: Client, db: SqliteDatabase, table: string, tableColumns: Column[]): Promise<number> {
  const names = tableColumns.map((column) => column.name);
  const rows = db.prepare(`SELECT * FROM ${quote(table)}`).all();
  const batchSize = 200;
  for (let offset = 0; offset < rows.length; offset += batchSize) {
    const batch = rows.slice(offset, offset + batchSize);
    const params: unknown[] = [];
    const values = batch.map((row, rowIndex) => {
      const placeholders = names.map((_name, columnIndex) => {
        params.push(row[names[columnIndex]] ?? null);
        return `$${rowIndex * names.length + columnIndex + 1}`;
      });
      return `(${placeholders.join(",")})`;
    });
    await client.query(`INSERT INTO ${quote(table)} (${names.map(quote).join(",")}) VALUES ${values.join(",")}`, params);
  }
  return rows.length;
}

async function resetTarget(client: Client, tables: string[]): Promise<void> {
  if (!tables.length) return;
  await client.query(`DROP TABLE IF EXISTS ${tables.map(quote).join(", ")} CASCADE`);
}

async function resetSequences(client: Client, table: string, tableColumns: Column[]): Promise<void> {
  const primary = tableColumns.filter((column) => column.pk > 0).sort((a, b) => a.pk - b.pk);
  if (primary.length !== 1 || !/INT/i.test(primary[0].type || "")) return;
  const column = primary[0].name;
  await client.query(
    `SELECT setval(pg_get_serial_sequence($1, $2), COALESCE((SELECT MAX(${quote(column)}) FROM ${quote(table)}), 1), true)`,
    [table, column],
  );
}

async function installImmutableTriggers(client: Client, tables: string[]): Promise<void> {
  const immutable = ["business_events", "stage_transitions"].filter((table) => tables.includes(table));
  if (!immutable.length) return;
  await client.query(`
    CREATE OR REPLACE FUNCTION prevent_immutable_row_change() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION '% is immutable', TG_TABLE_NAME USING ERRCODE = '55000';
    END;
    $$ LANGUAGE plpgsql;
  `);
  for (const table of immutable) {
    await client.query(`DROP TRIGGER IF EXISTS ${quote(`${table}_no_update`)} ON ${quote(table)}`);
    await client.query(`DROP TRIGGER IF EXISTS ${quote(`${table}_no_delete`)} ON ${quote(table)}`);
    await client.query(`CREATE TRIGGER ${quote(`${table}_no_update`)} BEFORE UPDATE ON ${quote(table)} FOR EACH ROW EXECUTE FUNCTION prevent_immutable_row_change()`);
    await client.query(`CREATE TRIGGER ${quote(`${table}_no_delete`)} BEFORE DELETE ON ${quote(table)} FOR EACH ROW EXECUTE FUNCTION prevent_immutable_row_change()`);
  }
}

export async function migrateSqliteToPostgres(input: {
  source: string;
  databaseUrl: string;
  replace?: boolean;
  verifyOnly?: boolean;
}): Promise<SqlitePostgresMigrationReport> {
  const sqlite = openSqliteReadOnly(input.source);
  const client = new Client({ connectionString: input.databaseUrl });
  await client.connect();
  try {
    const tables = sqliteTables(sqlite);
    if (!tables.length) throw new Error("SQLite source has no application tables");
    const metadata = new Map(tables.map((table) => [table, columns(sqlite, table)]));
    const existing = await client.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'");
    if (!input.verifyOnly) {
      if (existing.rows.length && !input.replace) {
        throw new Error("PostgreSQL target is not empty; refuse to overwrite. Use --replace only for a verified disposable target.");
      }
      await client.query("BEGIN");
      try {
        if (input.replace) await resetTarget(client, tables);
        for (const table of tables) await client.query(createTableSql(table, metadata.get(table)!));
        for (const table of tables) await copyRows(client, sqlite, table, metadata.get(table)!);
        for (const table of tables) {
          const tableColumns = metadata.get(table)!;
          for (const sql of indexSql(sqlite, table, tableColumns)) await client.query(sql);
          await resetSequences(client, table, tableColumns);
        }
        let constraintOrdinal = 0;
        for (const table of tables) {
          for (const key of foreignKeys(sqlite, table)) {
            constraintOrdinal += 1;
            await client.query(foreignKeySql(table, key, constraintOrdinal));
          }
        }
        await installImmutableTriggers(client, tables);
        await client.query("COMMIT");
      } catch (error) {
        await client.query("ROLLBACK");
        throw error;
      }
    }

    const report: MigrationTableReport[] = [];
    for (const table of tables) {
      const tableColumns = metadata.get(table)!;
      const sourceRows = sqlite.prepare(orderedRowsSql(table, tableColumns)).all();
      const target = await client.query(orderedRowsSql(table, tableColumns));
      if (sourceRows.length !== target.rows.length) throw new Error(`Row count mismatch for ${table}: sqlite=${sourceRows.length}, postgres=${target.rows.length}`);
      const sourceHash = migrationFingerprint(sourceRows, tableColumns);
      const targetHash = migrationFingerprint(target.rows, tableColumns);
      if (sourceHash !== targetHash) {
        const mismatched = mismatchedFingerprintColumns(sourceRows, target.rows, tableColumns);
        throw new Error(`Content fingerprint mismatch for ${table} (columns: ${mismatched.join(",") || "row-order"})`);
      }
      report.push({ table, rows: sourceRows.length, fingerprint: sourceHash });
    }
    return {
      source: input.source,
      target: input.databaseUrl.replace(/:\/\/[^@]+@/, "://***@"),
      tables: report,
      total_rows: report.reduce((sum, table) => sum + table.rows, 0),
      verified: true,
    };
  } finally {
    sqlite.close();
    await client.end();
  }
}
