/* Knowledge workspace visual prototype. All records are illustrative, all changes local to this page. */
const admin = document.body.dataset.mode === 'admin';
const taxonomy = [
 ['增长与合作','红人合作',['红人发现','建联邀约','合作执行','效果复盘']],
 ['增长与合作','内容营销',['选题策划','短视频脚本','内容审核','素材管理']],
 ['增长与合作','品牌运营',['品牌定位','传播活动','舆情应对','品牌资产']],
 ['交易与履约','供应链',['供应商开发','采购询价','质量管理','交付管理']],
 ['交易与履约','商品运营',['商品知识','商品上架','定价促销','库存管理']],
 ['交易与履约','客户服务',['安装售后','工单处理','退换货','客户反馈']],
 ['经营与管理','销售运营',['线索培育','商机跟进','报价方案','客户交接']],
 ['经营与管理','财务管理',['预算费用','结算付款','发票管理','对账核销']],
 ['经营与管理','法务合规',['合同管理','隐私保护','广告合规','知识产权']],
 ['组织与平台','人力行政',['入职指引','考勤休假','员工培训','行政采购']],
 ['组织与平台','数据分析',['指标口径','报表分析','实验评估','数据质量']],
 ['组织与平台','平台使用',['任务协作','知识管理','工具使用','故障处理']]
];
const names = ['红人筛选与信息核验清单','首次建联邮件与跟进模板','合作执行交付检查清单','合作效果复盘指南','月度内容选题方法','新品短视频脚本指南','商业内容发布前审核清单','素材命名与使用规范','品牌定位与表达手册','传播活动筹备清单','舆情分级响应指南','品牌视觉资产使用说明','核心供应商准入档案','供应商询价邮件模板','来料质量检查清单','交付延期处理指南','产品卖点与参数手册','商品上架校验清单','促销方案评审模板','库存异常排查指南','储能电池安装与保养手册','售后工单分级规则','北美退换货流程说明','客户反馈整理模板','海外展会客户跟进邮件','商机会议纪要模板','客户报价方案模板','客户交接核对清单','项目费用预算模板','合作结算材料清单','发票信息填写说明','月度对账与差异处理','合作合同审阅清单','客户信息使用规范','商业推广标识指南','素材授权核验清单','新员工入职指南','休假申请常见问题','岗位学习路径模板','行政采购申请说明','转化率指标口径','周度经营分析模板','内容实验评估指南','数据异常核验清单','任务协作使用指南','知识编写与维护规范','工具权限常见问题','任务异常恢复指引'];
const types=['操作指南','邮件模板','检查清单','复盘方法','制度规范','工作模板'];
const contentType=title=>/邮件/.test(title)?'邮件模板':/模板|档案/.test(title)?'工作模板':/清单/.test(title)?'检查清单':/规范|口径|规则|标识/.test(title)?'制度规范':/复盘|评估/.test(title)?'复盘方法':'操作指南';
const owners=['林予','周睿','顾言','苏晴'];
const records=taxonomy.flatMap(([family,domain,topics],di)=>topics.map((topic,ti)=>{
 const n=di*4+ti;
 return {id:n+1,family,domain,topic,title:names[n],type:contentType(names[n]),owner:owners[di%4],status:ti<2?'已发布':ti===2?'待审核':di%2?'草稿':'已停用',version:`V${n%5+1}`,date:`2026-09-${String(30-n%19).padStart(2,'0')}`,favorite:[1,6,14,25].includes(n+1),model:ti===1||ti===2?'结构化':'非结构化',carrier:di%3===0?'文件上传':'在线编辑',scope:di<3?'市场团队':'全体员工'};
}));
const state={query:'',domain:'',topic:'',view:'全部',type:'',selected:admin?3:1,tab:'内容',sort:'更新',recent:new Set([1]),expanded:false};
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name='file')=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${({file:'M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 16h6',book:'M3 5h7l2 2 2-2h7v15h-7l-2 1-2-1H3z M12 7v14',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',grid:'M4 4h6v6H4z M14 4h6v6h-6z M4 14h6v6H4z M14 14h6v6h-6z',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',menu:'M4 6h16 M4 12h16 M4 18h16',plus:'M12 5v14 M5 12h14',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2',mail:'M3 5h18v14H3z M3 5l9 8 9-8',person:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M4 21v-2a8 8 0 0 1 16 0v2',check:'M5 12l4 4L19 6',gear:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2'})[name]||'M4 4h16v16H4z'}"/></svg>`;
const statusHTML=r=>`<span class="status ${r.status==='待审核'?'review':r.status==='已发布'?'':'draft'}">${r.status==='已发布'?'✓ ':r.status==='待审核'?'◷ ':''}${r.status}</span>`;
function toast(message){$('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),4500)}
const employeeNav=['新任务','任务中心','定时任务','通讯','agent','技能','知识库','审批','考试','云盘','手机遥控电脑','创建新项目'];
const adminNav=['员工','连接','知识','审批','技能','考试','治理','数据','成本','配置'];
function shell(){
 const menu=admin?adminNav:employeeNav;
 $('#app').innerHTML=`<div class="shell"><aside class="side" aria-label="平台侧栏"><div class="brand">${icon('book')} KOL <small>${admin?'管理端':'员工端'}</small><button class="plain mobile-close" aria-label="关闭导航">×</button></div><nav aria-label="${admin?'管理端':'员工端'}导航">${menu.map((label,i)=>`${(admin?[1,4,5,7]:[4,5,6,11]).includes(i)?'<div class="nav-gap"></div>':''}<button class="nav-item ${label===(admin?'知识':'知识库')?'active':''}" ${!admin&&i>8?'disabled':''} ${label===(admin?'知识':'知识库')?'aria-current="page"':''} data-nav="${label}">${icon((admin?['person','grid','book','check','grid','file','person','grid','clock','gear']:['plus','clock','clock','mail','person','grid','book','check','file','grid','grid','plus'])[i])}<span>${label}</span>${!admin&&i>8?'<small>非本期</small>':''}</button>`).join('')}</nav><div class="account"><div class="account-line"><span><span class="avatar">林</span>林予</span><button class="plain" id="settings" aria-label="个人设置">${icon('gear')}</button></div><a href="space-3-${admin?'employee':'admin'}.html">查看${admin?'员工端':'管理端'}原型 ↗</a><small>设计预览 · 示例数据 · 未连接后端</small></div></aside><main><header class="top"><div class="heading"><button class="plain mobile-menu" aria-label="打开导航">${icon('menu')}</button><h1>${admin?'知识管理':'知识库'}</h1><span class="prototype">${admin?'维护可信、可用的知识':'找到可用于工作的知识'}</span></div><div class="actions">${admin?'<button id="taxonomy">分类目录</button><button id="new">新建知识</button>':'<small>仅展示已发布的示例知识</small>'}</div></header><div class="workspace"><section class="library" aria-label="知识检索"><div class="tools"><label class="search">${icon('search')}<input id="search" aria-label="搜索知识" placeholder="搜索标题、主题、负责人…" type="search"></label><div class="filters"><button id="category">全部领域 / 主题 ▾</button><select id="type" aria-label="知识类型"><option value="">全部类型</option>${types.map(t=>`<option>${t}</option>`).join('')}</select><button id="reset" class="plain" title="清除搜索和筛选">重置</button></div></div><div class="tabs" id="views"></div><div class="countline"><span id="count"></span><select id="sort" aria-label="排序"><option value="更新">最近更新</option><option value="标题">标题顺序</option></select></div><div class="records" aria-label="知识列表"></div><button class="plain more-mobile" style="display:none" id="more">展开全部结果</button></section><aside class="rail" aria-label="知识详情"></aside></div></main></div><dialog aria-labelledby="dialog-title"><div class="dialog-head"><h2 id="dialog-title"></h2><button class="plain" id="close-dialog" aria-label="关闭弹窗">×</button></div><div class="dialog-content"></div></dialog>`;
 $('.mobile-menu').onclick=()=>$('.side').classList.add('open');$('.mobile-close').onclick=()=>$('.side').classList.remove('open');
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>toast('此原型仅演示知识页；平台菜单保留原有入口。'));
 $('#settings').onclick=()=>toast('个人设置沿用现有平台页面。');
 $('#search').oninput=e=>{state.query=e.target.value;refresh()};$('#type').onchange=e=>{state.type=e.target.value;refresh()};$('#sort').onchange=e=>{state.sort=e.target.value;refresh()};
 $('#category').onclick=()=>categoryDialog(false);$('#reset').onclick=()=>{Object.assign(state,{query:'',domain:'',topic:'',view:'全部',type:''});$('#search').value='';$('#type').value='';refresh()};
 $('#more').onclick=()=>{state.expanded=!state.expanded;$('.records').classList.toggle('expanded',state.expanded);$('#more').textContent=state.expanded?'收起结果':'展开全部结果'};
 if(admin){$('#taxonomy').onclick=()=>categoryDialog(true);$('#new').onclick=()=>editDialog()}
 $('#close-dialog').onclick=()=>closeDialog();$('dialog').addEventListener('close',()=>{delete $('.shell').inert});
 refresh();
}
function available(){return records.filter(r=>admin||r.status==='已发布')}
function matchesView(r){return state.view==='全部'||state.view==='收藏'&&r.favorite||state.view==='最近查看'&&state.recent.has(r.id)||r.status===state.view}
function filtered(){return available().filter(r=>matchesView(r)&&(!state.domain||r.domain===state.domain)&&(!state.topic||r.topic===state.topic)&&(!state.type||r.type===state.type)&&[r.title,r.topic,r.domain,r.owner].some(v=>v.toLowerCase().includes(state.query.trim().toLowerCase()))).sort((a,b)=>state.sort==='更新'?b.date.localeCompare(a.date):a.title.localeCompare(b.title,'zh-CN'))}
function refresh(){
 const list=filtered();if(!list.some(r=>r.id===state.selected))state.selected=list[0]?.id||null;
 const views=admin?['全部','待审核','已发布','草稿','已停用']:['全部','收藏','最近查看'];
 $('#views').innerHTML=views.map(v=>{const count=available().filter(r=>v==='全部'||v==='收藏'&&r.favorite||v==='最近查看'&&state.recent.has(r.id)||r.status===v).length;return `<button class="tab" aria-pressed="${state.view===v}" data-view="${v}">${v} <small>${count}</small></button>`}).join('');
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;refresh()});
 $('#count').textContent=`${list.length} 条知识${state.domain?' · '+state.domain:''}`;$('#category').textContent=(state.topic?state.domain+' / '+state.topic:state.domain||'全部领域 / 主题')+' ▾';
 $('.records').innerHTML=list.length?list.map(r=>`<button class="record" data-id="${r.id}" aria-current="${r.id===state.selected}"><span class="file-icon">${icon(r.type==='邮件模板'?'mail':'file')}</span><span class="record-copy"><span class="record-title">${esc(r.title)}</span><span class="record-meta"><span>${r.domain} / ${r.topic}</span><span>· ${r.type}</span>${r.favorite&&!admin?'<span aria-label="已收藏">★</span>':''}</span></span><span class="record-end">${admin?statusHTML(r):`<span>${r.date.slice(5)}</span>`}<span class="muted">${admin?r.owner:r.version}</span></span></button>`).join(''):'<div class="empty"><h3>没有匹配的知识</h3><p>试试其他关键词，或重置领域和类型筛选。</p></div>';
 document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.id);state.recent.add(state.selected);state.tab='内容';refresh();if(innerWidth<=1100)$('.rail').scrollIntoView({behavior:'smooth',block:'start'})});
 detail();
}
function content(r){
 if(r.body)return `<section><h3>正文</h3><p style="white-space:pre-wrap">${esc(r.body)}</p></section>`;
 if(r.id===1)return `<section><h3>适用场景</h3><p>首次筛选创作者、复核合作候选名单。先核验账号身份与内容匹配度，再整理可供团队评审的依据。</p></section><section><h3>核验步骤</h3><ol class="steps"><li><strong>确认账号来源</strong><p>记录平台、主页链接、账号标识和信息采集时间，避免同名账号混淆。</p></li><li><strong>检查内容与品牌匹配度</strong><p>观察近期内容主题、受众和表达风格；引用具体作品链接，不以单一粉丝量作结论。</p></li><li><strong>记录证据与待确认项</strong><p>将已核验信息与推断分开，未知字段标记待确认，提交评审前保留来源。</p></li></ol></section><section><h3>交付结果</h3><p class="quote">候选账号 · 匹配依据 · 来源链接 · 待核验事项</p></section>`;
 if(r.id===3)return `<section><h3>交付检查</h3><ol class="steps"><li><strong>对齐已确认的合作约定</strong><p>核对内容形式、交付日期、素材要求和负责人，以关联合作记录为准。</p></li><li><strong>保留内容审核记录</strong><p>检查素材版本、审核意见与修改结果；涉及正式发布时另行执行授权流程。</p></li><li><strong>归档交付证据</strong><p>记录作品链接、交付时间和异常说明，供后续复盘使用。</p></li></ol></section><section><h3>本次修订</h3><p>补充了素材版本核验与异常交付的记录要求，等待审核。</p></section>`;
 return `<section><h3>适用场景</h3><p>用于${r.domain}中的${r.topic}工作。此处为“${r.title}”的版式示例，正式内容需由知识负责人维护。</p></section><section><h3>${r.model==='结构化'?'标准字段':'阅读提要'}</h3><ol class="steps"><li><strong>背景与目标</strong><p>记录当前工作背景、适用条件和所需输入。</p></li><li><strong>工作内容与核对项</strong><p>补齐关键材料，并核验所引用的来源及版本。</p></li><li><strong>结果与追溯</strong><p>记录负责人、产出和待确认事项，关联原始资料。</p></li></ol></section><section><h3>使用提醒</h3><p class="quote">示例内容不构成正式业务规则；使用前需核对适用范围与有效版本。</p></section>`;
}
function detail(){
 const r=records.find(x=>x.id===state.selected);if(!r){$('.rail').innerHTML='<div class="empty">选择一条知识，查看内容和来源。</div>';if(admin)$('#new').classList.add('primary');return}
 if(admin)$('#new').classList.toggle('primary',r.status!=='待审核'&&r.status!=='草稿');
 $('.rail').innerHTML=`<div class="detail-head"><div class="crumb">${r.family} / ${r.domain} / ${r.topic}</div><div class="title-row"><h2>${esc(r.title)}</h2>${!admin?`<button class="plain" id="favorite" aria-label="${r.favorite?'取消收藏':'收藏知识'}" aria-pressed="${r.favorite}">${r.favorite?'★':'☆'}</button>`:''}</div><div class="subtitle">${statusHTML(r)}<span>${r.version}</span><span>${r.owner} · ${r.date}</span></div></div><div class="tabs">${(admin?['内容','属性与范围','版本记录']:['内容','来源与版本']).map(t=>`<button class="tab" aria-pressed="${state.tab===t}" data-tab="${t}">${t}</button>`).join('')}</div><div class="detail-content">${state.tab==='内容'?`<div class="notice"><strong>${admin?(r.status==='待审核'?'待审核 · 修订内容尚未对员工生效':'维护提示'):'使用范围 · '+r.scope}</strong>${admin?'请核对正文、分类、适用范围和来源，再执行对应操作。':'用于任务时引用此版本；不会自动发送或执行知识中的动作。'}</div>${content(r)}<section><h3>来源材料</h3><p class="muted">${r.carrier==='文件上传'?esc(r.title)+'.docx · 文件上传':'在线编辑 · '+r.owner+' 维护'} · 示例来源</p></section>`:state.tab==='版本记录'?versions(r):properties(r)}</div><footer class="detail-footer"><small>${admin?'本页操作仅演示，不写入系统':'示例正文 · 使用前核对业务适用性'}</small><div class="actions">${admin?`<button id="edit">修订</button><button id="more-actions">更多 ▾</button>${r.status==='待审核'?'<button class="primary" id="review">审核</button>':r.status==='草稿'?'<button class="primary" id="submit">提交审核</button>':''}`:'<button class="primary" id="use">用于当前任务</button>'}</div></footer>`;
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;detail()});
 if(!admin){$('#favorite').onclick=()=>{r.favorite=!r.favorite;refresh();toast(r.favorite?'已收藏（本次原型会话）':'已取消收藏')};$('#use').onclick=()=>useDialog(r)}
 else{$('#edit').onclick=()=>editDialog(r);$('#more-actions').onclick=()=>moreActions(r);if($('#review'))$('#review').onclick=()=>reviewDialog(r);if($('#submit'))$('#submit').onclick=()=>confirmAction('提交审核',r,'待审核','仅将示例草稿送入待审核列表，不直接发布。')}
}
function properties(r){return `<dl class="properties"><div><dt>知识标识</dt><dd>KB-${String(r.id).padStart(4,'0')}</dd></div><div><dt>领域 / 主题</dt><dd>${r.domain} / ${r.topic}</dd></div><div><dt>适用范围</dt><dd>${r.scope} · 示例范围</dd></div><div><dt>维护责任人</dt><dd>${r.owner}</dd></div><div><dt>知识类型</dt><dd>${r.type}</dd></div>${admin?`<div><dt>内容模型 / 载体</dt><dd>${r.model} / ${r.carrier}</dd></div>`:''}<div><dt>来源</dt><dd>${r.carrier} · 示例资料；无真实附件</dd></div><div><dt>当前版本</dt><dd>${r.version} · ${r.date}</dd></div><div><dt>复核要求</dt><dd>尚未设置复核日期，待负责人确认</dd></div></dl>${!admin?'<section><h3>引用方式</h3><p class="muted">用于任务时保留知识标识、版本与来源；生产环境在引用时重新检查访问权限。</p></section>':''}`}
function versions(r){return `<div class="version"><h3>${r.version} · ${r.status}</h3><p>${r.date} · ${r.owner}</p><p class="muted">${r.note||'演示版本快照，仅用于展示当前内容。'}</p></div><p class="muted">未加载更早版本。本原型不虚构历史审批或发布记录。</p>`}
let returnFocus;
function openDialog(title,html){returnFocus=document.activeElement;$('#dialog-title').textContent=title;$('.dialog-content').innerHTML=html;document.querySelectorAll('main .primary').forEach(b=>b.classList.add('modal-primary-paused'));document.querySelectorAll('.modal-primary-paused').forEach(b=>b.classList.remove('primary'));if(!$('dialog').open)$('dialog').showModal()}
function closeDialog(){$('dialog').close();document.querySelectorAll('.modal-primary-paused').forEach(b=>{b.classList.remove('modal-primary-paused');b.classList.add('primary')});returnFocus?.focus()}
function categoryDialog(manage){
 openDialog(manage?'分类目录':'选择领域与主题',`<p class="muted">4 个主题域族 · 12 个领域 · 48 个主题。${manage?'分类管理入口集中在这里。':'按层级查找，也可直接搜索。'}</p><input id="tree-search" type="search" placeholder="搜索领域或主题" aria-label="搜索领域或主题"><div class="tree"></div>${manage?'<p class="muted">当前目录为设计示例。生产环境的新增、重命名与合并需校验引用，保留历史分类标识。</p>':''}`);
 function renderTree(q=''){const groups=[...new Set(taxonomy.map(t=>t[0]))];$('.tree').innerHTML=(!q?'<button data-domain="" data-topic="">全部领域与主题</button>':'')+groups.map(g=>{const rows=taxonomy.filter(t=>t[0]===g&&(t[1].includes(q)||t[2].some(x=>x.includes(q))));return rows.length?`<h3>${g}</h3>${rows.map(([f,d,ts])=>`<details ${q||d===(state.domain||'红人合作')?'open':''}><summary>${d} <small>· ${ts.length} 个主题</small></summary><div class="topics"><button data-domain="${d}" data-topic="">查看整个领域 <small>${available().filter(r=>r.domain===d).length} 条</small></button>${ts.filter(t=>d.includes(q)||t.includes(q)).map(t=>`<button data-domain="${d}" data-topic="${t}">${t}<small>${available().filter(r=>r.domain===d&&r.topic===t).length} 条</small></button>`).join('')}</div></details>`).join('')}`:''}).join('');if(!$('.tree').textContent.trim())$('.tree').innerHTML='<p class="empty">没有匹配的领域或主题</p>';document.querySelectorAll('[data-domain]').forEach(b=>b.onclick=()=>{state.domain=b.dataset.domain;state.topic=b.dataset.topic;state.view='全部';closeDialog();refresh()})}
 renderTree();$('#tree-search').oninput=e=>renderTree(e.target.value.trim());
}
function useDialog(r){openDialog('用于当前任务',`<div class="notice"><strong>${esc(r.title)} · ${r.version}</strong>将选定版本作为任务上下文，不执行外发或业务变更。</div><label>选择任务<select id="task"><option>红人合作前期资料整理（示例任务）</option><option>新建任务草稿（示例）</option></select></label><label>使用说明<textarea id="use-note" placeholder="例如：参考核验步骤，整理需要补充的信息"></textarea></label><p class="muted">这里只演示引用确认，不连接真实任务。</p><div class="dialog-actions"><button id="cancel">取消</button><button class="primary" id="confirm-use">演示添加引用</button></div>`);$('#cancel').onclick=closeDialog;$('#confirm-use').onclick=()=>{closeDialog();toast(`演示：已选择 KB-${String(r.id).padStart(4,'0')} ${r.version}，未写入真实任务。`)}}
function editDialog(r){
 openDialog(r?'修订知识 · 草稿':'新建知识 · 草稿',`<label>知识标题<input id="edit-title" required maxlength="120" value="${esc(r?.title||'')}" placeholder="使用具体、易检索的标题"></label><label>领域与主题<select id="edit-topic">${taxonomy.map(([f,d,ts])=>`<optgroup label="${f} / ${d}">${ts.map(t=>`<option value="${d}|${t}" ${r?.topic===t?'selected':''}>${t}</option>`).join('')}</optgroup>`).join('')}</select></label><label>知识类型<select id="edit-type">${types.map(t=>`<option ${r?.type===t?'selected':''}>${t}</option>`).join('')}</select></label><label>内容模型<select id="edit-model"><option ${r?.model==='结构化'?'selected':''}>结构化</option><option ${!r||r.model==='非结构化'?'selected':''}>非结构化</option></select></label><label>内容载体<select id="edit-carrier"><option ${r?.carrier==='在线编辑'?'selected':''}>在线编辑</option><option ${r?.carrier==='文件上传'?'selected':''}>文件上传</option></select></label><div id="upload-box" hidden><label>选择来源文件<input id="upload" type="file" accept=".pdf,.docx,.txt,.md,.png,.jpg"></label><p class="muted">原型仅记录文件名；实际提取需后台作业与失败恢复。</p></div><label>正文 / 修订说明<textarea id="edit-body" placeholder="输入知识正文，或说明此次修订内容">${esc(r?.body||'')}</textarea></label><p class="error" id="edit-error" role="alert"></p><div class="dialog-actions"><button id="cancel">取消</button><button class="primary" id="save">保存示例草稿</button></div>`);
 const toggle=()=>$('#upload-box').hidden=$('#edit-carrier').value!=='文件上传';toggle();$('#edit-carrier').onchange=toggle;
 $('#cancel').onclick=closeDialog;$('#save').onclick=()=>{const title=$('#edit-title').value.trim(),body=$('#edit-body').value.trim();if(!title||!body){$('#edit-error').textContent='请填写标题与正文 / 修订说明。';return}const [domain,topic]=$('#edit-topic').value.split('|');const published=r?.status==='已发布';const item={...(r||{}),id:published||!r?Math.max(...records.map(x=>x.id))+1:r.id,title,domain,topic,family:taxonomy.find(t=>t[1]===domain)[0],type:$('#edit-type').value,model:$('#edit-model').value,carrier:$('#edit-carrier').value,status:'草稿',body,owner:r?.owner||'林予',scope:r?.scope||'待设置',version:published?`V${Number(r.version.slice(1))+1}（草稿）`:r?.version||'V1',date:'2026-10-02',note:published?`基于 ${r.version} 创建修订草稿，已发布版本保持可用。`:'原型中保存的草稿'};if(r&&!published)Object.assign(r,item);else records.push(item);Object.assign(state,{selected:item.id,query:'',domain:'',topic:'',view:'草稿',type:'',tab:'内容'});$('#search').value='';$('#type').value='';closeDialog();refresh();toast('草稿已保存在本次页面会话；刷新后恢复示例数据。')}
}
function reviewDialog(r){openDialog('审核知识',`<div class="notice"><strong>${esc(r.title)} · ${r.version}</strong>范围：${r.scope}；分类：${r.domain} / ${r.topic}</div><label>审核意见<textarea id="review-note" placeholder="说明通过或退回的依据"></textarea></label><p class="muted">此处仅演示状态变化，生产环境由服务端校验审核权限并保存回执。</p><p class="error" id="review-error" role="alert"></p><div class="dialog-actions"><button id="reject">退回修改</button><button class="primary" id="publish">确认演示发布</button></div>`);const finish=status=>{if(!$('#review-note').value.trim()){$('#review-error').textContent='请填写审核意见。';return}r.note=$('#review-note').value.trim();r.status=status;if(status==='已发布')r.version=r.version.replace('（草稿）','');closeDialog();refresh();toast('演示状态已更新，未执行真实审核或发布。')};$('#reject').onclick=()=>finish('草稿');$('#publish').onclick=()=>finish('已发布')}
function confirmAction(title,r,status,description){openDialog(title,`<p>${esc(r.title)}</p><p class="muted">${description}</p><div class="dialog-actions"><button id="cancel">取消</button><button class="primary" id="confirm">确认演示${title}</button></div>`);$('#cancel').onclick=closeDialog;$('#confirm').onclick=()=>{r.status=status;closeDialog();refresh();toast('仅更新本页示例状态。')}}
function moreActions(r){openDialog('知识维护',`<button id="scope">调整适用范围</button><button id="history">查看版本记录</button><button id="deactivate" ${r.status!=='已发布'?'disabled':''}>停用已发布版本</button><p class="muted">正式写入前需再次确认并保留审计回执。</p>`);$('#history').onclick=()=>{closeDialog();state.tab='版本记录';detail()};$('#deactivate').onclick=()=>{closeDialog();confirmAction('停用',r,'已停用','演示停用后将不再出现在员工可用列表中。已有任务引用仍需保留版本快照。')};$('#scope').onclick=()=>{closeDialog();openDialog('调整适用范围',`<label>可见范围<select id="scope-value"><option>全体员工</option><option>市场团队</option><option>知识维护组</option></select></label><p class="muted">范围为示例选项；生产环境从组织授权服务获取。</p><div class="dialog-actions"><button id="cancel">取消</button><button class="primary" id="save-scope">确认演示调整</button></div>`);$('#cancel').onclick=closeDialog;$('#save-scope').onclick=()=>{r.scope=$('#scope-value').value;closeDialog();detail();toast('已调整示例范围，未修改真实权限。')}}}
shell();
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.modal-primary-paused').forEach(b=>{b.classList.remove('modal-primary-paused');b.classList.add('primary')});$('.side').classList.remove('open')}});

// Explicit file intake and contextual approval navigation (prototype, no network writes).
const uploadFormats={pdf:'PDF 文档',doc:'Word 文档',docx:'Word 文档',xls:'Excel 表格',xlsx:'Excel 表格',csv:'CSV 表格',ppt:'演示文稿',pptx:'演示文稿',txt:'纯文本',md:'Markdown',html:'HTML 文档',png:'图片 / 待 OCR',jpg:'图片 / 待 OCR',jpeg:'图片 / 待 OCR',webp:'图片 / 待 OCR'};
const originalDetail=detail;
detail=function(){
 originalDetail();if(!admin)return;
 const r=records.find(x=>x.id===state.selected);if(!r)return;
 const footer=$('.detail-footer .actions');
 if(r.status==='待审核'||r.reviewed){const link=document.createElement('a');link.className='approval-link';link.id='go-approval';link.href='#approvals?knowledge='+r.id;link.textContent=r.status==='待审核'?'前往审批 ↗':'查看审批 ↗';footer.prepend(link)}
 if(r.attachment){const section=document.createElement('section');section.innerHTML=`<h3>来源文件</h3><p>${esc(r.attachment.name)}</p><p class="muted">${esc(r.attachment.format)} · ${formatSize(r.attachment.size)} · 本地已选择，未上传 / 未提取</p>`;$('.detail-content').prepend(section);if($('#submit')){$('#submit').disabled=true;$('#submit').title='文件需完成真实上传、提取与内容核对后才能提交审核'}}
};
function formatSize(size){return size<1024?size+' B':size<1048576?(size/1024).toFixed(1)+' KB':(size/1048576).toFixed(1)+' MB'}
function uploadDialog(){
 let files=[];
 openDialog('上传文件',`<p>支持批量选择或拖入文件，每个文件形成一条待整理草稿。</p><div id="drop-zone" class="file-info"><label>选择文件<input id="batch-files" type="file" multiple accept="${Object.keys(uploadFormats).map(x=>'.'+x).join(',')}"></label><p class="muted">PDF · Word · Excel / CSV · PowerPoint · TXT / Markdown / HTML · PNG / JPG / WEBP</p></div><p class="muted">格式仅表示本原型可选择的文件类型；实际解析、OCR 与上传限制待后端能力确认。</p><label>统一归档领域与主题<select id="batch-topic">${taxonomy.map(([f,d,ts])=>`<optgroup label="${f} / ${d}">${ts.map(t=>`<option value="${d}|${t}">${t}</option>`).join('')}</optgroup>`).join('')}</select></label><div id="file-queue" aria-live="polite"></div><p class="error" id="file-error" role="alert"></p><div class="dialog-actions"><button id="cancel">取消</button><button id="save-files" class="primary" disabled>创建文件草稿（演示）</button></div>`);
 function render(){ $('#file-queue').innerHTML=files.map((f,i)=>`<div class="file-row"><div><strong>${esc(f.name)}</strong><p class="muted">${uploadFormats[f.name.split('.').pop().toLowerCase()]} · ${formatSize(f.size)} · 待上传</p></div><button data-remove-file="${i}" aria-label="移除 ${esc(f.name)}">移除</button></div>`).join('');$('#save-files').disabled=!files.length;document.querySelectorAll('[data-remove-file]').forEach(b=>b.onclick=()=>{files.splice(Number(b.dataset.removeFile),1);render()}) }
 function add(incoming){const errors=[];for(const f of incoming){const ext=f.name.split('.').pop().toLowerCase();if(!uploadFormats[ext]){errors.push(f.name+'：格式暂不支持');continue}if(!f.size){errors.push(f.name+'：空文件');continue}if(files.some(x=>x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified)){errors.push(f.name+'：已在列表中');continue}files.push(f)}$('#file-error').textContent=errors.join('；');render()}
 $('#batch-files').onchange=e=>{add([...e.target.files]);e.target.value=''};
 $('#drop-zone').ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'};$('#drop-zone').ondrop=e=>{e.preventDefault();add([...e.dataTransfer.files])};$('#cancel').onclick=closeDialog;
 $('#save-files').onclick=()=>{const [domain,topic]=$('#batch-topic').value.split('|');let selected;for(const f of files){selected=Math.max(...records.map(r=>r.id))+1;records.push({id:selected,title:f.name.replace(/\.[^.]+$/,''),family:taxonomy.find(t=>t[1]===domain)[0],domain,topic,type:'操作指南',owner:'林予',status:'草稿',version:'V1',date:'2026-10-02',scope:'待设置',model:'非结构化',carrier:'文件上传',body:'文件已在本地选择。尚未上传或提取正文，接入文件服务后需核对提取内容，再提交审批。',attachment:{name:f.name,size:f.size,format:uploadFormats[f.name.split('.').pop().toLowerCase()]}})}Object.assign(state,{selected,view:'草稿',query:'',domain:'',topic:'',type:'',tab:'内容'});$('#search').value='';$('#type').value='';closeDialog();refresh();toast(`已创建 ${files.length} 条本地文件草稿；文件尚未上传，刷新后不保留。`)};
}
function approvalRoute(){
 if(!admin)return;const active=location.hash.startsWith('#approvals');
 $('.top').hidden=active;$('.workspace').hidden=active;
 document.querySelectorAll('[data-nav]').forEach(b=>{const current=b.dataset.nav===(active?'审批':'知识');b.classList.toggle('active',current);if(current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
 $('.approval-page')?.remove();if(!active)return;
 const id=Number(new URLSearchParams(location.hash.split('?')[1]||'').get('knowledge'));const rows=records.filter(r=>r.status==='待审核'||r.reviewed);const r=rows.find(x=>x.id===id)||(id?null:rows[0]);
 const page=document.createElement('section');page.className='approval-page';page.innerHTML=`<header class="top"><div class="heading"><h1>审批</h1><span class="muted">知识发布 · 跳转演示</span></div><a href="#knowledge" id="back-knowledge">← 返回知识管理</a></header><div class="approval-body"><div class="notice">这里演示知识与审批的关联跳转。正式入口沿用 /admin/approvals；示例记录不是真实审批单。</div><label>关联知识<select id="approval-picker">${rows.map(x=>`<option value="${x.id}" ${x.id===r?.id?'selected':''}>${esc(x.title)} · ${x.status}</option>`).join('')}</select></label>${r?`<section><h2>${esc(r.title)}</h2><p class="subtitle">${statusHTML(r)}<span>${r.version}</span><span>${r.owner}</span></p><dl class="properties"><div><dt>申请事项</dt><dd>知识发布 · ${r.domain} / ${r.topic}</dd></div><div><dt>适用范围</dt><dd>${esc(r.scope)}</dd></div><div><dt>审批状态</dt><dd>${r.reviewed?'本页演示已处理：'+esc(r.note):'待审核（示例）；审批人及链路需从正式服务获取'}</dd></div></dl></section><section>${content(r)}</section><div class="actions"><a href="#knowledge" id="approval-source">返回关联知识</a>${r.status==='待审核'?'<button class="primary" id="approval-review">审核此知识</button>':''}</div>`:'<p>当前没有对应的示例审批记录。可返回知识管理查看其他内容。</p>'}</div>`;
 $('main').append(page);$('#approval-picker').onchange=e=>location.hash='approvals?knowledge='+e.target.value;
 if(r){$('#approval-source').onclick=()=>{state.selected=r.id;state.view='全部';state.query='';state.domain='';state.topic='';state.type='';$('#search').value='';$('#type').value='';refresh()};if($('#approval-review'))$('#approval-review').onclick=()=>{reviewDialog(r);const publish=$('#publish').onclick,reject=$('#reject').onclick;$('#publish').onclick=()=>{publish();if(!$('dialog').open){r.reviewed=true;approvalRoute()}};$('#reject').onclick=()=>{reject();if(!$('dialog').open){r.reviewed=true;approvalRoute()}}}}
}
if(admin){const upload=document.createElement('button');upload.id='upload-files';upload.textContent='上传文件';upload.onclick=uploadDialog;$('#new').before(upload);$('[data-nav="审批"]').onclick=()=>{location.hash='approvals'};$('[data-nav="知识"]').onclick=()=>{location.hash='knowledge'};addEventListener('hashchange',approvalRoute);detail();approvalRoute()}
