[Service]
WorkingDirectory=/home/ecs-user/kol-releases/main-task-operations-2254b59c
Environment=LINGONG_DATA=/home/ecs-user/kol/data
ExecStart=
ExecStart=/home/ecs-user/kol-releases/main-task-operations-2254b59c/scripts/start.sh
